"""Add gst_rate to Product table

Revision ID: 59c148e1195a
Revises: 3a17b729c232
Create Date: 2025-09-22 16:33:37.651962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59c148e1195a'
down_revision: Union[str, Sequence[str], None] = '3a17b729c232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('gst_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'gst_rate')
    # ### end Alembic commands ###
